import About from '@/components/screens/about/About'
import type { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'About',
	description: 'Generated by create next app',
}

const AboutPage = () => {
	return <About />
}

export default AboutPage
