import './globals.scss'
import { ReactNode } from 'react'
import type { Metadata } from 'next'
import Header from '@/components/layout/header/Header'
import Providers from '@/providers/Providers'

export const metadata: Metadata = {
	title: { template: '%s | Next App', default: 'Home | Next App' },
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
	return (
		<html lang='ru'>
			<body>
				<Providers>
					<Header />
					<main>{children}</main>
				</Providers>
			</body>
		</html>
	)
}
