import Blog from '@/components/screens/blog/Blog'
import { Metadata } from 'next'

export const metadata: Metadata = {
	title: 'Blog',
	description: 'Generated by create next app',
}

const BlogPage = () => {
	return <Blog />
}

export default BlogPage
